barstool_sports_data_pipeline:
  outputs:
    dev:
      dataset: barstool_sports_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../gcp_service_account_key.json
      location: US
      method: service-account
      priority: interactive
      project: barstool-sports-461005
      threads: 4
      type: bigquery
  target: dev
